### ISSUE TITLE
Payment type 6

### ISSUE THREAD

**Issue by toooni** [z38/swiss-payment#1]
I would like to implement payment type 6 because we need to make payments to foreign countries (in other currencies than CHF). Can you tell me if it's correct to implement just V3 (Name and address of
FI International)?

**Comment by z38** [comment]
Disclaimer: I haven't used payment type 6 in production yet.

As far as I read the corresponding business rules, payment type 6 is indeed quite similar to type 3. I spotted the following differences:
- The name and address of the creditor agent (the foreign bank) can be provided in case the BIC is not known
- The charge bearer (DEBT, CRED, SHAR, SLEV) can be indicated
- Support for all account numbers (not just IBAN)

You could implement this type by extending from `Z38\SwissPayment\TransactionInformation\CreditTransfer` and building the message in a similar manner as in `BankCreditTransfer`. In case you are interested, I could implement these additions within the next few days.

**Comment by toooni** [comment]
Thank you for your answer.I'll check again if type 6 is really the one we need. I will make a PR if you like, so you don't have to bother..
