### ISSUE TITLE
getSoftwareVersion - release

### ISSUE THREAD

**Issue by einenlum** [z38/swiss-payment#10]
Shouldn't you put the name of the latest release [here](https://github.com/z38/swiss-payment/blob/master/src/Z38/SwissPayment/Message/AbstractMessage.php#L75), instead of `dev-master`?

**Comment by z38** [comment]
You're right, in most cases we should put the release there. It didn't come up with a good way to do it yet.

Updating the version before a release and resetting back to `dev-master` after the release would result in two commits for each release. Maybe we need to adopt a new branching model.

Do you have any suggestions?

**Comment by z38** [comment]
As of [v0.4.0](https://github.com/z38/swiss-payment/commit/dc7adba50455d3a509a59bceaa76bc8ed516bd02) the version property is updated whenever a new release gets out. Thank you for the report!

**Comment by einenlum** [comment]
:+1:
