### ISSUE TITLE
How to use it ...

### ISSUE THREAD

**Issue by haycoin** [z38/swiss-payment#13]
Hi All, 
I've installed composer and swiss-payment and trying to run CustomerCreditTransferTest.

I'm not familiar with composer ... i've create a new file test.php with : 

```
<?php
ini_set('display_errors', 1);
error_reporting(~0);

include_once '/var/www/html/composer/vendor/z38/swiss-payment/tests/Z38/SwissPayment/Tests/Message/CustomerCreditTransferTest.php';

$tc = new TestCase();
echo $tc; 
echo 'End';

```

I got a 

> Fatal error: Class 'Z38\SwissPayment\Tests\TestCase' not found in /var/www/html/composer/vendor/z38/swiss-payment/tests/Z38/SwissPayment/Tests/Message/CustomerCreditTransferTest.php on line 26

Could you please help me to start using your libraries ?

Thanks, best regards.

**Comment by haycoin** [comment]
I got my reply ready this 

https://github.com/z38/swiss-payment/issues/5

... maybe you should add an example file ... or i can do it :) if you wish 

You can close this question

**Comment by z38** [comment]
Thank you for your feedback! A runnable example would definitely help to get started.

To improve the situation, I [added](https://github.com/z38/swiss-payment/commit/d18289536730e4b86a3731e17200921f76a26069) a small example to the README. If you have any further suggestions on how to get new users started, please feel free to comment.

**Comment by haycoin** [comment]
That's perfect !
Thanks for you great job :)
