### ISSUE TITLE
Purpose (Purp) 

### ISSUE THREAD

**Issue by nenad007** [z38/swiss-payment#14]
How I could set the Purpose <Purp> of the Payment? 
Should I extend the class ForeignCreditTransfer and BankCreditTransfer or did I miss something?

**Comment by z38** [comment]
You're right, this isn't possible yet. In #15 in you can find a proposal for an implementation.

Example:
```
$transaction->setPurpose(new \Z38\SwissPayment\TransactionInformation\PurposeCode('AIRB'));
```

Note: If you need to make salary or pension payments (`SALA`/`PENS`), you have set the purpose on B-level (the [Swiss Business Rules](https://www.six-interbank-clearing.com/dam/downloads/en/standardization/iso/swiss-recommendations/business-rules.pdf) contain quite a few remarks on how to proceed in this case):
```
$payment->setCategoryPurpose(new \Z38\SwissPayment\PaymentInformation\CategoryPurposeCode('SALA'));
```

Please let me know if you have any remarks on the implementation or when you need more control over the transaction. As soon as you're able to accomplish your project, I will release a new version.

**Comment by nenad007** [comment]
Thank you, the Implementation is great, it's flexible enoigh this way, I think the Impelementation of purpose is a good benefit for everyone, as SALA/PENS is widely used for payments  in Switzerland.
