### ISSUE TITLE
Sanitize strings to never render invalid XML regarding the XSD

### ISSUE THREAD

**Issue by sdespont** [z38/swiss-payment#21]
In my point of view, the library must never render invalid XML regarding the XSD. 

Today, a creditor name like "Mrs & Mr Smith" throw an error because of "&" char is not escaped. Also, using funny chars like "§, "°" or others which cannot be displayed by user copy-paste manipulation) in the remittance information of payment type 3 for example render an XML not valid and will be rejected by the banks.

Therefore, I suggest to enforce the following parts of code to ensure that there is no unvalid characters in the strings:
- StructuredPostalAddress
- UnstructuredPostalAddress
- TransactionInformation creditorName parameter
- CreditTransfer/setRemittanceInformation

It could be done by sanitize all strings using a common function :

```
    /**
     * @param string $text
     * @return string
     */
    private function escapeText(string $text, int $maxLength)
    {
        $san1 = htmlspecialchars($text, ENT_XML1);
        $san2 = preg_replace("/[^a-zA-Z0-9\.,;:'\+\-\/\(\)?\*\[\]\{\}\\`´~ !&quot;#%&amp;&lt;&gt;÷=@_\$£ àáâäçèéêëìíîïñòóôöùúûüýßÀÁÂÄÇÈÉÊËÌÍÎÏÒÓÔÖÙÚÛÜÑ]+/u", '-', $san1);

        return substr($san2, 0, $maxLength);
    }
```

Also, `AbstractMessage/asXml` method could have a bolean parameter to validate the generated string with the XSD, and returns false if the validation failed.

What is your opinion?

**Comment by z38** [comment]
Thank you for raising this important point! The library should definitely handle such cases. I was under the assumption that `DOMDocument::createElement` does escape the content. You can find a fix for this issue in #22. Feel free to comment if you have any suggestions or think an other approach might work better.

**Comment by z38** [comment]
I'd like to thank you for your valuable time and effort you put into implementing this addition. As of [version 0.6.0](https://github.com/z38/swiss-payment/releases/tag/v0.6.0), the situation should be much better now. Please feel free to open a new issue if you encounter any problems or see room for improvement!

**Comment by sdespont** [comment]
@z38 This release is a great step! First real tests today have worked well 👍 
Thanks again for your work.
