### ISSUE TITLE
Enforce floating point conversion error

### ISSUE THREAD

**Issue by sdespont** [z38/swiss-payment#27]
Should we add `round()` before `intval()` to avoid potential "[Floating point precision](https://stackoverflow.com/questions/20213661/float-to-int-error)"? 

An example to depict the problem : https://eval.in/993353

https://github.com/z38/swiss-payment/blob/b8e0a3cc75467e9d8aa6cf2d0341e1b03b5910fe/src/Z38/SwissPayment/Money/Money.php#L15-L23

**Comment by a-schild** [comment]
Yep, would be nice.
To just truncate the decimals isn't what we expect.

We did do this round in our code, before calling the Meony constructor

**Comment by z38** [comment]
Thank you for pointing out this issue. I included your fix in 862fafa. However, I still recommend to work with integers whenever possible. Especially, if you do some kind of balancing the implicit conversion might lead to unexpected results.

**Comment by sdespont** [comment]
@z38 Yes, but sometimes values are stored in database using [DECMIAL ](https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html)format and we need to deal with that...
