### ISSUE TITLE
ISO20022

### ISSUE THREAD

**Issue by bradydan** [z38/swiss-payment#29]
Are you available for freelance development regarding ISO 20022 PAIN version 6 messages? (sorry to contact you via this method)

**Comment by z38** [comment]
Hi Dan, I'm sorry you had to wait such a long time for an answer. Unfortunately, I'm not available for freelance work at the moment (as you might have guessed from my long response time).

However, please feel free to open an issue if any problems or questions regarding the library or the payment process in general arise.
