### ISSUE TITLE
Installing it on debian squeeze

### ISSUE THREAD

**Issue by hausi14** [z38/swiss-payment#5]
I was able to install composer, then i started in /home/tests

composer require z38/swiss-payment

which created the folder vendor. When I start in folder:

/home/tests/vendor/z38/swiss-payment/tests/Z38/SwissPayment/Tests/Message

the example

php CustomerCreditTransferTest.php

I get erros:

PHP Fatal error:  Class 'Z38\SwissPayment\Tests\TestCase' not found in /home/test/vendor/z38/swiss-payment/tests/Z38/SwissPayment/Tests/Message/CustomerCreditTransferTest.php on line 24
/home/tests/vendor/z38/swiss-payment/tests/Z38/SwissPayment/Tests/Message

What could be the reason for the errors?

**Comment by z38** [comment]
The errors are probably thrown because the file was invoked directly.
If you run `phpunit tests/Z38/SwissPayment/Tests/Message/CustomerCreditTransferTest.php` it should run properly.

**Comment by hausi14** [comment]
It worked after install phpunit. So I can call phpunit:

phpunit tests/Z38/SwissPayment/Tests/Message/CustomerCreditTransferTest.php
PHPUnit 3.4.14 by Sebastian Bergmann.
Time: 0 seconds, Memory: 8.00Mb
OK (2 tests, 3 assertions)

My question now is, where can I find the resulting xml file?

**Comment by z38** [comment]
Oh I see, in case you want to see a sample message: The following snippet shows how to generate a file for a single transaction:

``` php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Z38\SwissPayment\BIC;
use Z38\SwissPayment\IBAN;
use Z38\SwissPayment\Message\CustomerCreditTransfer;
use Z38\SwissPayment\Money;
use Z38\SwissPayment\PaymentInformation\PaymentInformation;
use Z38\SwissPayment\StructuredPostalAddress;
use Z38\SwissPayment\TransactionInformation\BankCreditTransfer;

$transaction = new BankCreditTransfer(
    'instr-001',
    'e2e-001',
    new Money\CHF(130000), // CHF 1300.00
    'Muster Transport AG',
    new StructuredPostalAddress('Wiesenweg', '14b', '8058', 'Zürich-Flughafen'),
    new IBAN('CH51 0022 5225 9529 1301 C'),
    new BIC('UBSWCHZH80A')
);

$payment = new PaymentInformation(
    'payment-001',
    'InnoMuster AG',
    new BIC('ZKBKCHZZ80A'),
    new IBAN('CH6600700110000204481')
);
$payment->addTransaction($transaction);

$message = new CustomerCreditTransfer('message-001', 'InnoMuster AG');
$message->addPayment($payment);

echo $message->asXml();
```

In `CustomerCreditTransferTest::buildMessage()` you can see how all supported transaction types are used. Feel free to ask in case you have any questions or need another transaction type. I'm happy to help ;)

**Comment by hausi14** [comment]
Wow, I just added the first transaction to my ebanking account. ZKB processed the file without any complaints.

Is there somewhere any documentation or do I just need to look through the source code?

For example, if I call

$transaction1 = new BankCreditTransfer(
    'instr-002',
    'e2e-001',
    new Money\CHF(131000), // CHF 1310.00
    'Muster Pizza AG',
    new StructuredPostalAddress('Pizzaweg', '15b', '8006', 'Zürich'),
    new IBAN('CH51 0022 5225 9529 2504 D'),
    new BIC('UBSWCHZH80A')
);

$payment->addTransaction($transaction1);

Is this the correct way to add a second transaction to the same xml file?

**Comment by z38** [comment]
Exactly, just add them using `$payment->addTransaction()`. In case you make SEPA payments the transactions should be wrapped in a separate `Z38\SwissPayment\PaymentInformation\SEPAPaymentInformation`. Other payments in foreign currencies might need to be grouped in a separate `PaymentInformation` as well.

I would recommend building a test file which contains all transaction types you need and testing the file with ZKB. In addition you might want to look into [the guidelines and the SIX validation portal](https://github.com/z38/swiss-payment#further-resources).
